# coding: utf-8

"""
    ROM Store API

    API for querying, managing and accessing a TOSEC ROM store.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.ping_api import PingApi


class TestPingApi(unittest.TestCase):
    """PingApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PingApi()

    def tearDown(self) -> None:
        pass

    def test_root_get(self) -> None:
        """Test case for root_get

        Root
        """
        pass


if __name__ == '__main__':
    unittest.main()
