# coding: utf-8

"""
    ROM Store API

    API for querying, managing and accessing a TOSEC ROM store.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.collection_api import CollectionApi


class TestCollectionApi(unittest.TestCase):
    """CollectionApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CollectionApi()

    def tearDown(self) -> None:
        pass

    def test_games_by_platform_collection_by_platform_platform_id_get(self) -> None:
        """Test case for games_by_platform_collection_by_platform_platform_id_get

        Games By Platform
        """
        pass

    def test_missing_files_by_platform_collection_missing_by_platform_platform_id_get(self) -> None:
        """Test case for missing_files_by_platform_collection_missing_by_platform_platform_id_get

        Missing Files By Platform
        """
        pass

    def test_missing_files_by_platform_count_collection_missing_by_platform_count_platform_id_get(self) -> None:
        """Test case for missing_files_by_platform_count_collection_missing_by_platform_count_platform_id_get

        Missing Files By Platform Count
        """
        pass


if __name__ == '__main__':
    unittest.main()
