# coding: utf-8

"""
    ROM Store API

    API for querying, managing and accessing a TOSEC ROM store.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.game_api import GameApi


class TestGameApi(unittest.TestCase):
    """GameApi unit test stubs"""

    def setUp(self) -> None:
        self.api = GameApi()

    def tearDown(self) -> None:
        pass

    def test_read_games_by_platform_game_by_platform_platform_id_get(self) -> None:
        """Test case for read_games_by_platform_game_by_platform_platform_id_get

        Read Games By Platform
        """
        pass

    def test_search_games_game_search_get(self) -> None:
        """Test case for search_games_game_search_get

        Search Games
        """
        pass


if __name__ == '__main__':
    unittest.main()
