# coding: utf-8

"""
    ROM Store API

    API for querying, managing and accessing a TOSEC ROM store.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.datfile_api import DatfileApi


class TestDatfileApi(unittest.TestCase):
    """DatfileApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DatfileApi()

    def tearDown(self) -> None:
        pass

    def test_upload_datfile_datfile_upload_post(self) -> None:
        """Test case for upload_datfile_datfile_upload_post

        Upload Datfile
        """
        pass


if __name__ == '__main__':
    unittest.main()
