# coding: utf-8

"""
    ROM Store API

    API for querying, managing and accessing a TOSEC ROM store.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.auth_api import AuthApi


class TestAuthApi(unittest.TestCase):
    """AuthApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AuthApi()

    def tearDown(self) -> None:
        pass

    def test_login_for_access_token_auth_token_post(self) -> None:
        """Test case for login_for_access_token_auth_token_post

        Login For Access Token
        """
        pass

    def test_register_user_auth_register_post(self) -> None:
        """Test case for register_user_auth_register_post

        Register User
        """
        pass


if __name__ == '__main__':
    unittest.main()
