# coding: utf-8

"""
    ROM Store API

    API for querying, managing and accessing a TOSEC ROM store.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.gamefile_api import GamefileApi


class TestGamefileApi(unittest.TestCase):
    """GamefileApi unit test stubs"""

    def setUp(self) -> None:
        self.api = GamefileApi()

    def tearDown(self) -> None:
        pass

    def test_read_game_files_by_game_gamefile_by_game_game_id_get(self) -> None:
        """Test case for read_game_files_by_game_gamefile_by_game_game_id_get

        Read Game Files By Game
        """
        pass

    def test_read_game_files_by_platform_gamefile_by_platform_platform_id_get(self) -> None:
        """Test case for read_game_files_by_platform_gamefile_by_platform_platform_id_get

        Read Game Files By Platform
        """
        pass

    def test_search_game_files_gamefile_search_post(self) -> None:
        """Test case for search_game_files_gamefile_search_post

        Search Game Files
        """
        pass


if __name__ == '__main__':
    unittest.main()
