# coding: utf-8

"""
    ROM Store API

    API for querying, managing and accessing a TOSEC ROM store.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.platform_api import PlatformApi


class TestPlatformApi(unittest.TestCase):
    """PlatformApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PlatformApi()

    def tearDown(self) -> None:
        pass

    def test_read_platforms_platform_get(self) -> None:
        """Test case for read_platforms_platform_get

        Read Platforms
        """
        pass

    def test_search_platforms_platform_search_get(self) -> None:
        """Test case for search_platforms_platform_search_get

        Search Platforms
        """
        pass


if __name__ == '__main__':
    unittest.main()
