# coding: utf-8

"""
    ROM Store API

    API for querying, managing and accessing a TOSEC ROM store.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class GameFileSearchFilter(BaseModel):
    """
    GameFileSearchFilter
    """ # noqa: E501
    id: Optional[StrictInt] = None
    name: Optional[StrictStr] = None
    demo: Optional[StrictBool] = None
    system: Optional[StrictStr] = None
    video: Optional[StrictStr] = None
    country: Optional[StrictStr] = None
    language: Optional[StrictStr] = None
    dev_status: Optional[StrictStr] = None
    media: Optional[StrictStr] = None
    copyright: Optional[StrictStr] = None
    cracked: Optional[StrictBool] = None
    fixed: Optional[StrictBool] = None
    hacked: Optional[StrictBool] = None
    modified: Optional[StrictBool] = None
    pirated: Optional[StrictBool] = None
    trained: Optional[StrictBool] = None
    translated: Optional[StrictBool] = None
    overdumped: Optional[StrictBool] = None
    underdumped: Optional[StrictBool] = None
    virus: Optional[StrictBool] = None
    baddump: Optional[StrictBool] = None
    alternate: Optional[StrictBool] = None
    verified: Optional[StrictBool] = None
    platform_id: Optional[StrictInt] = None
    game_id: Optional[StrictInt] = None
    rom_count: Optional[StrictInt] = None
    __properties: ClassVar[List[str]] = ["id", "name", "demo", "system", "video", "country", "language", "dev_status", "media", "copyright", "cracked", "fixed", "hacked", "modified", "pirated", "trained", "translated", "overdumped", "underdumped", "virus", "baddump", "alternate", "verified", "platform_id", "game_id", "rom_count"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GameFileSearchFilter from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if id (nullable) is None
        # and model_fields_set contains the field
        if self.id is None and "id" in self.model_fields_set:
            _dict['id'] = None

        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict['name'] = None

        # set to None if demo (nullable) is None
        # and model_fields_set contains the field
        if self.demo is None and "demo" in self.model_fields_set:
            _dict['demo'] = None

        # set to None if system (nullable) is None
        # and model_fields_set contains the field
        if self.system is None and "system" in self.model_fields_set:
            _dict['system'] = None

        # set to None if video (nullable) is None
        # and model_fields_set contains the field
        if self.video is None and "video" in self.model_fields_set:
            _dict['video'] = None

        # set to None if country (nullable) is None
        # and model_fields_set contains the field
        if self.country is None and "country" in self.model_fields_set:
            _dict['country'] = None

        # set to None if language (nullable) is None
        # and model_fields_set contains the field
        if self.language is None and "language" in self.model_fields_set:
            _dict['language'] = None

        # set to None if dev_status (nullable) is None
        # and model_fields_set contains the field
        if self.dev_status is None and "dev_status" in self.model_fields_set:
            _dict['dev_status'] = None

        # set to None if media (nullable) is None
        # and model_fields_set contains the field
        if self.media is None and "media" in self.model_fields_set:
            _dict['media'] = None

        # set to None if copyright (nullable) is None
        # and model_fields_set contains the field
        if self.copyright is None and "copyright" in self.model_fields_set:
            _dict['copyright'] = None

        # set to None if cracked (nullable) is None
        # and model_fields_set contains the field
        if self.cracked is None and "cracked" in self.model_fields_set:
            _dict['cracked'] = None

        # set to None if fixed (nullable) is None
        # and model_fields_set contains the field
        if self.fixed is None and "fixed" in self.model_fields_set:
            _dict['fixed'] = None

        # set to None if hacked (nullable) is None
        # and model_fields_set contains the field
        if self.hacked is None and "hacked" in self.model_fields_set:
            _dict['hacked'] = None

        # set to None if modified (nullable) is None
        # and model_fields_set contains the field
        if self.modified is None and "modified" in self.model_fields_set:
            _dict['modified'] = None

        # set to None if pirated (nullable) is None
        # and model_fields_set contains the field
        if self.pirated is None and "pirated" in self.model_fields_set:
            _dict['pirated'] = None

        # set to None if trained (nullable) is None
        # and model_fields_set contains the field
        if self.trained is None and "trained" in self.model_fields_set:
            _dict['trained'] = None

        # set to None if translated (nullable) is None
        # and model_fields_set contains the field
        if self.translated is None and "translated" in self.model_fields_set:
            _dict['translated'] = None

        # set to None if overdumped (nullable) is None
        # and model_fields_set contains the field
        if self.overdumped is None and "overdumped" in self.model_fields_set:
            _dict['overdumped'] = None

        # set to None if underdumped (nullable) is None
        # and model_fields_set contains the field
        if self.underdumped is None and "underdumped" in self.model_fields_set:
            _dict['underdumped'] = None

        # set to None if virus (nullable) is None
        # and model_fields_set contains the field
        if self.virus is None and "virus" in self.model_fields_set:
            _dict['virus'] = None

        # set to None if baddump (nullable) is None
        # and model_fields_set contains the field
        if self.baddump is None and "baddump" in self.model_fields_set:
            _dict['baddump'] = None

        # set to None if alternate (nullable) is None
        # and model_fields_set contains the field
        if self.alternate is None and "alternate" in self.model_fields_set:
            _dict['alternate'] = None

        # set to None if verified (nullable) is None
        # and model_fields_set contains the field
        if self.verified is None and "verified" in self.model_fields_set:
            _dict['verified'] = None

        # set to None if platform_id (nullable) is None
        # and model_fields_set contains the field
        if self.platform_id is None and "platform_id" in self.model_fields_set:
            _dict['platform_id'] = None

        # set to None if game_id (nullable) is None
        # and model_fields_set contains the field
        if self.game_id is None and "game_id" in self.model_fields_set:
            _dict['game_id'] = None

        # set to None if rom_count (nullable) is None
        # and model_fields_set contains the field
        if self.rom_count is None and "rom_count" in self.model_fields_set:
            _dict['rom_count'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GameFileSearchFilter from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "demo": obj.get("demo"),
            "system": obj.get("system"),
            "video": obj.get("video"),
            "country": obj.get("country"),
            "language": obj.get("language"),
            "dev_status": obj.get("dev_status"),
            "media": obj.get("media"),
            "copyright": obj.get("copyright"),
            "cracked": obj.get("cracked"),
            "fixed": obj.get("fixed"),
            "hacked": obj.get("hacked"),
            "modified": obj.get("modified"),
            "pirated": obj.get("pirated"),
            "trained": obj.get("trained"),
            "translated": obj.get("translated"),
            "overdumped": obj.get("overdumped"),
            "underdumped": obj.get("underdumped"),
            "virus": obj.get("virus"),
            "baddump": obj.get("baddump"),
            "alternate": obj.get("alternate"),
            "verified": obj.get("verified"),
            "platform_id": obj.get("platform_id"),
            "game_id": obj.get("game_id"),
            "rom_count": obj.get("rom_count")
        })
        return _obj


