# coding: utf-8

# flake8: noqa

"""
    ROM Store API

    API for querying, managing and accessing a TOSEC ROM store.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "AuthApi",
    "CollectionApi",
    "DatfileApi",
    "GameApi",
    "GamefileApi",
    "PingApi",
    "PlatformApi",
    "SearchApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "CountResponse",
    "Game",
    "GameFile",
    "GameFileListWithLimitOffset",
    "GameFileSearchFilter",
    "GameListWithLimitOffset",
    "GameSearchFilter",
    "HTTPValidationError",
    "LoginData",
    "Platform",
    "PlatformList",
    "PlatformSearchFilter",
    "SearchFilter",
    "SearchResult",
    "SearchResultWithLimitOffset",
    "Token",
    "ValidationError",
    "ValidationErrorLocInner",
]

# import apis into sdk package
from openapi_client.api.auth_api import AuthApi as AuthApi
from openapi_client.api.collection_api import CollectionApi as CollectionApi
from openapi_client.api.datfile_api import DatfileApi as DatfileApi
from openapi_client.api.game_api import GameApi as GameApi
from openapi_client.api.gamefile_api import GamefileApi as GamefileApi
from openapi_client.api.ping_api import PingApi as PingApi
from openapi_client.api.platform_api import PlatformApi as PlatformApi
from openapi_client.api.search_api import SearchApi as SearchApi

# import ApiClient
from openapi_client.api_response import ApiResponse as ApiResponse
from openapi_client.api_client import ApiClient as ApiClient
from openapi_client.configuration import Configuration as Configuration
from openapi_client.exceptions import OpenApiException as OpenApiException
from openapi_client.exceptions import ApiTypeError as ApiTypeError
from openapi_client.exceptions import ApiValueError as ApiValueError
from openapi_client.exceptions import ApiKeyError as ApiKeyError
from openapi_client.exceptions import ApiAttributeError as ApiAttributeError
from openapi_client.exceptions import ApiException as ApiException

# import models into sdk package
from openapi_client.models.count_response import CountResponse as CountResponse
from openapi_client.models.game import Game as Game
from openapi_client.models.game_file import GameFile as GameFile
from openapi_client.models.game_file_list_with_limit_offset import GameFileListWithLimitOffset as GameFileListWithLimitOffset
from openapi_client.models.game_file_search_filter import GameFileSearchFilter as GameFileSearchFilter
from openapi_client.models.game_list_with_limit_offset import GameListWithLimitOffset as GameListWithLimitOffset
from openapi_client.models.game_search_filter import GameSearchFilter as GameSearchFilter
from openapi_client.models.http_validation_error import HTTPValidationError as HTTPValidationError
from openapi_client.models.login_data import LoginData as LoginData
from openapi_client.models.platform import Platform as Platform
from openapi_client.models.platform_list import PlatformList as PlatformList
from openapi_client.models.platform_search_filter import PlatformSearchFilter as PlatformSearchFilter
from openapi_client.models.search_filter import SearchFilter as SearchFilter
from openapi_client.models.search_result import SearchResult as SearchResult
from openapi_client.models.search_result_with_limit_offset import SearchResultWithLimitOffset as SearchResultWithLimitOffset
from openapi_client.models.token import Token as Token
from openapi_client.models.validation_error import ValidationError as ValidationError
from openapi_client.models.validation_error_loc_inner import ValidationErrorLocInner as ValidationErrorLocInner

